languageCode = "en-us"
title = "Massively"
baseURL = "https://hugo-theme-massively.netlify.com/"
theme = "../.."

[params.posts]
    foldername = "post"
    pagesize = "6"
    featuredpost = "true"

[params.settings]
    googleanalytics = "UA-113904582-4"
    disqus = "hugo-massively"

[languages]
[languages.en]
  languageName = "English"
[languages.es]
  languageName = "Español"
  title = "Massively - Versión Español"
